[package]
name = "gamepad2midi"
version = "0.1.0"
authors = ["Aaron Miller <aaron@crate.im>"]
edition = "2018"

[dependencies]
gilrs = "0.8.2"
log = "0.4.14"
pretty_env_logger = "0.4.0"
eyre = "0.6.6"
midir = "0.7.0"
toml = "0.5.8"
wmidi = "4.0.6"
