[package]
name = "gamepad2midi"
version = "0.1.0"
authors = ["Aaron Miller <aaron@crate.im>"]
edition = "2018"

[dependencies]
gilrs = { version = "0.7.4" }
log = "0.4.11"
pretty_env_logger = "0.4.0"
eyre = "0.6.0"
midir = "0.6.2"
toml = "0.5.6"
wmidi = "3.1.0"
